# Define a gem dependency
source 'https://rubygems.org'

gem 'colorize', '~> 1.0'  # Example gem for colored console output

# Group dependencies (optional)
group :development do
  gem 'byebug'  # Example gem for debugging
  gem 'terminal-table'
  gem 'gem mysql2'
  gem 'yaml'
  gem 'erb'
end